services:
  server-jvm:
    image: quarkus-lab/server-jvm:${TAG:-latest}
    build:
      context: ./server
      dockerfile: Dockerfile.jvm
    container_name: server-jvm
    ports:
      - "8080:8080"
    healthcheck:
      # The /q/health/live endpoint is provided by the quarkus-smallrye-health extension.
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - lab-network

  server-native:
    image: quarkus-lab/server-native:${TAG:-latest}
    build:
      context: ./server
      dockerfile: Dockerfile.native
    container_name: server-native
    ports:
      - "8081:8080"
    healthcheck:
      # The health check targets the internal port 8080.
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - lab-network

  demo-client:
    image: quarkus-lab/demo-client:${TAG:-latest}
    build:
      context: ./demo-client
      dockerfile: Dockerfile
    container_name: demo-client
    ports:
      - "8082:80"
    depends_on:
      server-jvm:
        condition: service_healthy
      server-native:
        condition: service_healthy
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge