services:
  server-jvm:
    # Build the image from the Dockerfile.jvm located in the 'server' directory.
    build:
      context: ./server
      dockerfile: Dockerfile.jvm
    container_name: quarkus-lab-jvm
    ports:
      - "8080:8080"
    environment:
      # It tells Quarkus to listen on all network interfaces inside the container, not just localhost.
      - QUARKUS_HTTP_HOST=0.0.0.0
    healthcheck:
      # The /q/health/live endpoint is provided by the quarkus-smallrye-health extension.
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  server-native:
    build:
      context: ./server
      dockerfile: Dockerfile.native
    container_name: quarkus-lab-native
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
    healthcheck:
      # The health check targets the internal port 8080.
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health/live" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  demo-client:
    build:
      context: ./demo-client
      dockerfile: Dockerfile
    container_name: quarkus-lab-client
    ports:
      - "8082:80"
    depends_on:
      server-jvm:
        condition: service_healthy
      server-native:
        condition: service_healthy